# gmtinfo

```julia
gmtinfo(cmd0::String="", arg1=nothing; kwargs...)
```

Find the extreme values in data tables.

Description
-----------

**gmtinfo** reads {{< gmtref GMTdataset type=gmttype >}} [or from files] and finds the extreme values
in each of the columns reported as slash-separated min/max pairs. It recognizes NaNs and will print
warnings if the number of columns vary from record to record. The pairs can be split into two separate
columns by using the **numeric** option. As another option, **gmtinfo** can find the extent of data in
the first two columns rounded up and down to the nearest multiple of the supplied increments given by
**inc**. Such output will be in the text form -R*w/e/s/n*, which can be used directly on the command
line for other modules (hence only *dx* and *dy* are needed). If **numeric** is combined with **inc**
then the output will be in column form and rounded up/down for as many columns as there are increments
provided in **inc**. A similar option (**nearest_multiple**) will provide a -T*zmin/zmax/dz* string
for {{< gmtref makecpt >}}.

Required Arguments
------------------

*table*
   One or more data tables (file name, GMTdataset, or matrix). When using file nmaes, and want to apply
   to more than one, `arg1` can be a tuple or vector of file names.

Optional Arguments
------------------

- **A** | **ranges** : -- *ranges=:a* **|** *ranges=:t* **|** *ranges=:s*\
   Specify how the range should be reported. Choose `ranges=:a` for the range of all tables combined, `ranges=:t` to report the range for each table separately, and `ranges=:s` to report the range for each segment (in multisegment tables) separately. [Default is `ranges=:a`].

- **C** | **numeric** | **per_column** : -- *numeric=true*\
   Report the min/max values per column in separate columns [Default uses <min/max> format]. When used, users may also use **outcols** to limit which output columns should be reported [all].

- **D** | **center** : -- *center=true* **|** *center=(dx, dy)*\
   Modifies results obtained by **inc** by shifting the region to better align with the center of the data. Optionally, append granularity for this shift [Default performs an exact shift].

- **E** | **get_record** : -- *get_record=:l* **|** *get_record=:h* **|** *get_record=:L* **|** *get_record=:H* **|** *get_record="l5"*\
   Returns the record whose column *col* contains the minimum (**l**) or maximum (**h**) value. Upper case (**L**|**H**) works on absolute value of the data. In case of multiple matches, only the first record is returned. If *col* is not specified we default to the last column in the data.

- **F** | **counts** : -- *counts=:i* **|** *counts=:d* **|** *counts=:t*\
   Returns the counts of various records depending on the appended mode: **i** returns a single record with the total number of tables, segments, data records, header records, and overall records. In contrast, **d** returns information for each segment in the virtual data set: *tbl_number, seg_number, n_rows, start_rec, stop_rec*. Mode **t** does the same but honors the input table organization and thus resets *seg_number, start_rec, stop_rec* at the start of each new table [Default is **i**].

- **I** | **inc** | **increment** | **spacing** : -- *inc=val* **|** *inc=(dx, dy)* **|** *inc=(exact=true, inc=val)* **|** *inc=(surface=true, inc=val)* **|** *inc=(fft=true, inc=val)* **|** *inc=(polyg=true,)*\
   Compute the *min*/*max* values of the first *n* columns to the nearest multiple of the provided increments (separate the *n* increments by slashes) [default is 2 columns]. By default, output results in the string -R*w/e/s/n* or -R*xmin/xmax/ymin/ymax*, unless **numeric** is set in which case we output each *min* and *max* value in separate output columns. Several directives are available:

   - **polyg=true** - Write the bounding box of the data table or segments (see **ranges**) as a closed polygon segment.
   - **exact=true** - The exact *min*/*max* of the input is given in the -R string.
   - **fft=true** - Report an extended region optimized to give grid dimensions for fastest results in programs using FFTs.
   - **surface=true** - Report an extended region optimized to give grid dimensions for fastest results in programs like {{< gmtref surface >}}.

- **L** | **common_limits** : -- *common_limits=true*\
   Determines common limits across tables (`ranges=:t`) or segments (`ranges=:s`). If used with **inc** it will round inwards so that the resulting bounds lie within the actual data domain.

- **T** | **nearest_multiple** : -- *nearest_multiple=dz* **|** *nearest_multiple=(dz=val, col=n)*\
   Report the min/max of the first (0'th) column to the nearest multiple of *dz* and output this as the string -T*zmin/zmax/dz*. To use another column, append **col=n**. Cannot be used together with **inc**. **Note**: If your column has absolute time then you may append a valid fixed time unit to *dz* (i.e., choose from **w**eek, **d**ay, **h**our, **m**inute, or **s**econd).

{{< include ../common_opts/opt_V.qmd >}}

{{< include ../common_opts/opt_a.qmd >}}

{{< include ../common_opts/opt_bi.qmd >}}

{{< include ../common_opts/opt_di.qmd >}}

{{< include ../common_opts/opt_e.qmd >}}

{{< include ../common_opts/opt_f.qmd >}}

{{< include ../common_opts/opt_g.qmd >}}

{{< include ../common_opts/opt_h.qmd >}}

{{< include ../common_opts/opt__i.qmd >}}

{{< include ../common_opts/opt_o.qmd >}}

{{< include ../common_opts/opt_qi.qmd >}}

{{< include ../common_opts/opt__r.qmd >}}

{{< include ../common_opts/opt_s.qmd >}}

{{< include ../common_opts/opt__w.qmd >}}

- **yx** : -- *yx=true*\
   Swap 1st and 2nd column on input and/or output.

Examples
--------

To find the extreme values in the remote file @ship_15.txt:

```{julia}
using GMT
gmtinfo("@ship_15.txt")
```

Output should look like:

```
ship_15.txt: N = 82651	<245/254.705>	<20/29.99131>	<-4504/-9>
```

To find the extreme values in @ship_15.txt to the nearest 5 units but shifted to within 1 unit of the data center, and use this region to plot all the points as small black circles:

```{julia}
R = gmtinfo("@ship_15.txt", inc=5, center=1)
plot("@ship_15.txt", region=R[3:end], frame=:auto, marker=:circ, ms="2p", show=true)
```

To find the min and max values for each of the first 3 columns, but rounded to integers, and return the result individually for each data file:

```{julia}
gmtinfo("@ship_15.txt", numeric=true, inc="1/1/1")
```

The file magprofs.txt contains a number of magnetic profiles stored as separate data segments. We need to know how many segments there are:

```julia
gmtinfo("magprofs.txt", counts=:i)
```

Bugs
----

The **inc** option does not yet work properly with time series data (e.g., `incols="0T"`). Thus, such variable intervals as months and years are not calculated. Instead, specify your interval in the same units as the current setting of TIME_UNIT.

```{julia}
#| echo: false
#| output: asis
using GMT
GMT.doc_source_links("gmtinfo")
```

See Also
--------

- {{< gmtref gmtconvert >}}, {{< gmtref plot >}}
- [Alphabetical Function List](../alphabetical.html)
