# mask

```julia
mask(cmd0::String="", arg1=[]; kwargs...)

or

mask(GI:GItype, shapes::GMTdataset, touches=false, inverse::Bool=false, maskvalues=??)

or

mask(G::GMTgrid, M, value::Real=NaN)
mask(I::GMTimage, M, value=UInt8(0); alpha=false)
```

Clip or mask map areas with no data table coverage

Description
-----------

Reads (*x*, *y*, *z*) tables (or a file) and uses this information to find out which grid cells are reliable.
Only grid cells which have one or more data points are considered reliable. As an option, you may specify a 
radius of influence. Then, all grid cells that are within *radius* of a data point are considered reliable.
Furthermore, an option is provided to reverse the sense of the test.  Having found the reliable/not reliable
points, the module will either paint tiles to mask these nodes (with the **tiles** switch), or use contouring
to create polygons that will clip out regions of no interest. When clipping is initiated, it will stay in effect
until turned off by a second call to the module using the **endclip** option.

A second method expects a {{< gmtref GMTgrid type=gmttype >}} or an {{< gmtref GMTimage type=gmttype >}} as first argument and a
{{< gmtref GMTdataset type=gmttype >}} in second and will clip the grid/image to the selected region(s) defined
in polygons of the second argument. Grids are clipped to the global BoundingBox of the polygons and
images are copped to that limit and set to transparent in the regions outside of the polygons.
This method uses GDAL to compute the clipping mask. Used together with the ``DCW`` option of
{{< gmtref coast >}} this is very handy to clip rasters to country or {{< gmtref earthregions >}} boundaries.
Note that this method is in a way similar to one of the {{< gmtref grdlandmask >}} methods. The
difference is that here use a external polygon description that may be read from any _OGR_ vector file
whilst {{< gmtref grdlandmask >}} uses the GSHHG dataset.

A third method applies a mask array directly to a grid or image. Where the mask is nonzero (true, 1, or 255),
the corresponding grid or image values are replaced by a given value (NaN by default for grids, 0 for images).
The mask can be a `BitMatrix`, `Matrix{Bool}`, `Matrix{UInt8}` (with 0/1 or 0/255 values), or another
{{< gmtref GMTgrid type=gmttype >}} or {{< gmtref GMTimage type=gmttype >}}. For color images, the replacement
value can be an RGB tuple.

Required Arguments (1st method)
-------------------------------

- *table*\
    One or more data tables holding a number of data columns.

{{< include ../common_opts/opt_I.qmd >}}

{{< include ../common_opts/opt_J.qmd >}}

{{< include ../common_opts/opt_R.qmd >}}

{{< include ../common_opts/opt_R_3D.qmd >}}

Required Arguments (2nd method)
-------------------------------

- `GI`: A grid ({{< gmtref GMTgrid type=gmttype >}}) or image ({{< gmtref GMTimage type=gmttype >}}) to be clipped.

- `shapes`: A {{< gmtref GMTdataset type=gmttype >}} or a vector of them containing the polygons outside which the elements of `GI` will be clipped

Optional Arguments
------------------

{{< include ../common_opts/opt_B.qmd >}}

- **C** or **endclip** or **end_clip_path** : -- *endclip=true*\
    Mark end of existing clip path. No input file is needed. Also supply **xshift** and **yshift**
    settings if you have moved since the clip started.

- **D** or **dump** : -- *dump=fname*\
    Dump the (x,y) coordinates of each clipping polygon to one or more output files (or in-memory array).
    No plotting will take place. If *template* contains the C-format specifier %d (including modifications
    like %05d) then polygons will be written to different files; otherwise all polygons are written to the
    specified file (*template*). The files are ASCII unless **binary_out** is used. See **cut_number**
    to exclude small polygons from consideration.

- **F** or **oriented** : -- *oriented=:left* **|** *oriented=true* **|** *oriented=:right*\
    Force clip contours (polygons) to be oriented so that data points are to the
    left ([Default]) or right (**oriented=:right**) as we move along the perimeter
    [Default is arbitrary orientation]. Requires **dump**.

- **G** or **fill** : -- *fill=color*\
    Paint the clip polygons (or tiles) with a selected fill [Default is no fill].

- **Jz** or **JZ** or *zscale* or *zsize* : *zscale=scale* **|** *zsize=size*\
   Set z-axis scaling or or z-axis size. ``zsize=size`` sets the size to the fixed value *size*
   (for example *zsize=10* or *zsize=4i*). ``zscale=scale`` sets the vertical scale to UNIT/z-unit.

- **L** or **nodegrid** : -- *nodegrid="gridname"* **|** *nodegrid="gridname+i"* **|** *nodegrid="gridname+o"\
    Save the internal grid with ones (data constraint) and zeros (no data) to the named *gridname*. Append **+o**
    to convert the outside (no data) nodes to NaNs before writing the grid, while appending **+i** will instead
    convert the inside (data) flags to NaNs. Omitting the *gridname*, as in **nodegrid=true** or **nodegrid="+i"**
    returns a grid as a {{< gmtref GMTgrid type=gmttype >}} object.

- **N** or **inverse** : -- *inverse=true*\
    Invert the sense of the test, i.e., clip regions where there is data coverage.

- **Q** or **cut** or **cut_number** : -- *cut=n*
    Do not dump polygons with less than *cut* number of points [Dumps all polygons]. Only applicable if
    **dump** has been specified.

- **S** or **search_radius** : -- *search_radius=rad*\
    Sets radius of influence. Grid nodes within *radius* of a data point are considered reliable. [Default is 0,
    which means that only grid cells with data in them are reliable]. Append the distance unit (see [Units]).

- **T** or **tiles** : -- *tiles=true*\
    Plot tiles instead of clip polygons. Use **fill** to set tile color or pattern. Cannot be used with **dump**.

- `touches`: For the grid/image method, include all cells/pixels that are touched by the polygons. The default is
  to include only the cells whose centers that are inside the polygons.

{{< include ../common_opts/opt_U.qmd >}}

{{< include ../common_opts/opt_V.qmd >}}

{{< include ../common_opts/opt_X.qmd >}}

{{< include ../common_opts/opt_Y.qmd >}}

{{< include ../common_opts/opt_bi.qmd >}}

{{< include ../common_opts/opt_di.qmd >}}

{{< include ../common_opts/opt_e.qmd >}}

{{< include ../common_opts/opt_h.qmd >}}

{{< include ../common_opts/opt__i.qmd >}}

{{< include ../common_opts/opt_p.qmd >}}

{{< include ../common_opts/opt_q.qmd >}}

{{< include ../common_opts/opt__r.qmd >}}

{{< include ../common_opts/opt_t.qmd >}}

{{< include ../common_opts/opt__w.qmd >}}

{{< include ../common_opts/opt_xy.qmd >}}

{{< include ../common_opts/opt__distunits.qmd >}}

{{< include ../common_opts/opt_save_fig.qmd >}}

Arguments (3rd method)
----------------------

- `G` or `I`: The target {{< gmtref GMTgrid type=gmttype >}} or {{< gmtref GMTimage type=gmttype >}} to which the mask will be applied.

- `M`: A mask array. Can be a {{< gmtref GMTgrid type=gmttype >}}, {{< gmtref GMTimage type=gmttype >}}, `BitMatrix`,
  `Matrix{Bool}`, or `Matrix{UInt8}` (with values 0/1 or 0/255). Where the mask is true (nonzero), the corresponding
  elements of `G` or `I` are replaced by `value`.

- `value`: The replacement value. For grids, defaults to `NaN`. For images, defaults to `UInt8(0)`. For color
  (multi-band) images, `value` can be an RGB tuple, e.g., `(255, 0, 0)` for red. Ignored when `alpha=true`.

- `alpha`: When `true` (images only), instead of painting the masked pixels, an alpha channel is added to the
  image making the masked regions fully transparent. Single-band images are automatically promoted to RGB.
  This is the same transparency mechanism used by the 2nd method (polygon clipping).

Examples
--------

To make a mask that has a 5 degree radius around points spaced every 10 degree
along the prime meridian, and just paint those areas yellow we try::


```{julia}
using GMT
t = [repeat([0],19) -90:10:90]      # Some fake data
mask(t, fill=:yellow, inc="30m", region=(-75,75,-90,90), proj=:eqc, search_radius="5d", tiles=true,
     title="Mask for points with r = 5 degrees", xaxis=(annot=:auto, ticks=:auto, grid=180),
     yaxis=(annot=:auto, ticks=:auto, grid=10), show=true)
```


To make an overlay that will mask out the regions of a
contour map where there is no control data using clip polygons, use:

```julia
    gmt mask africa_grav.xyg -R20/40/20/40 -I5m -JM10i -pdf mask
```

We do it again, but this time we wish to save the clipping polygons to file all_pols.txt:

```julia
    gmt mask africa_grav.xyg -R20/40/20/40 -I5m -Dall_pols.txt
```

A repeat of the first example but this time we use white tiling:

```julia
    gmt mask africa_grav.xyg -R20/40/20/40 -I5m -JM10i -T -Gwhite -pdf mask
```



```{julia}
using GMT

D = coast(DCW=:HR, dump=true);      # Extract the Croatia border from the DCW
I = gmtread("@earth_day_30s", region=D, V=:q);  # Load Earth image containing Croatia
Ic = mask(I, D);                    # Mask outside (make image transparent there)

gmtwrite("Ic.tiff", Ic)             # For now we need to save and reload to see
Ic = gmtread("Ic.tiff");            # the tranparency in action.

viz(Ic, title="Croatia")
```



Apply a mask array to a grid — set masked cells to NaN::

```{julia}
using GMT

G = mat2grid(rand(Float32, 64, 64));              # A random 64×64 grid
msk = falses(64, 64);  msk[20:40, 20:40] .= true; # Mask a central block
Gm = mask(G, msk);                                # Masked cells become NaN
viz(Gm, title="Grid with masked block")
```

```{julia}
#| echo: false
#| output: asis
using GMT
GMT.doc_source_links("mask")
```

See Also
--------


{{< gmtref grdmask >}}, {{< gmtref surface >}}, {{< gmtref basemap >}}, {{< gmtref clip >}}
