# x2sys_put

```julia
x2sys_put(cmd0::String="", arg1=nothing; kwargs...)
```

Update x2sys track database from track bin-index file.

(**Warning: Manual translate by Claude. Needs revision**)

Description
-----------

**x2sys_put** accepts a track bin-index file created by {{< gmtref x2sys_binlist >}}
and adds this information about the data tracks to the relevant data base. You may
choose to overwrite existing data with new information for older tracks (**force**)
and even completely remove information for certain tracks (**delete**). The x2sys
TAG must match the tag encoded in the *info.tbf* file. To inquire about tracks in
the data base, use {{< gmtref x2sys_get >}}.

Required Arguments
------------------

- *info.tbf* : -- Name of a single track bin file (file name or GMTdataset).
   If not given, standard input will be read.

- **T** or **TAG** or **tag** : -- *tag="tagname"*\
   Specify the system tag for this compilation.

Optional Arguments
------------------

- **D** or **delete** : -- *delete=true*\
   Delete all tracks found in the track bin file [Default will try to add them
   as new track entries].

- **F** or **force** or **replace** : -- *force=true*\
   Replace any existing database information for these tracks with the new
   information in the track bin file [Default refuses to process tracks already
   in the database].

{{< include ../common_opts/opt_V.qmd >}}

X2sys Databases
---------------

The **x2sys_put** utility adds new information to the x2sys data bases. These
consist of two files:

1. **TAG_tracks.txt** - ASCII file containing a listing of all tracks added to the system
2. **TAG_index.b** - native binary file containing information on which tracks cross
   each bin and what data sets were observed

The bins are defined by the **region** and **inc** options passed to {{< gmtref x2sys_init >}}
when the TAG was first initiated. Both data base files are stored in the
**$X2SYS_HOME**/*TAG* directory. Do not attempt to edit these files by hand.

Examples
--------

To add the information stored in the track bin-index file latest.tbf to the track
data bases associated with the tag MGD77, and replace any existing information
for these tracks:

```julia
using GMT
x2sys_put("latest.tbf", tag="MGD77", force=true)
```

To add new tracks without replacing existing ones:

```julia
using GMT
x2sys_put("newtracks.tbf", tag="MGD77")
```

To delete tracks from the database:

```julia
using GMT
x2sys_put("oldtracks.tbf", tag="MGD77", delete=true)
```

Typical Workflow
----------------

```julia
using GMT

# 1. Create bin-index file from track data
x2sys_binlist("track1.dat track2.dat", tag="MYTAG") |> write("tracks.tbf")

# 2. Add to database
x2sys_put("tracks.tbf", tag="MYTAG")

# 3. Query which tracks are in a region
x2sys_get(tag="MYTAG", region=(0,10,0,10))
```

See Also
--------

- {{< gmtref x2sys_init >}}, {{< gmtref x2sys_binlist >}}, {{< gmtref x2sys_get >}}, {{< gmtref x2sys_cross >}}
- [Alphabetical Function List](../alphabetical.html)

```{julia}
#| echo: false
#| output: asis
using GMT
GMT.doc_source_links("x2sys_put")
```
