# x2sys_datalist

```julia
x2sys_datalist(cmd0::String="", arg1=nothing; kwargs...)
```

Extract data from track files.

(**Warning: Manual translate by Claude. Needs revision**)

Description
-----------

**x2sys_datalist** reads one or more files and produces a single ASCII
(or binary) table. The files can be of any format; this information is
encoded in the TAG set with the **tag** option. You may limit the output
to a geographic region, and insist that the output from several files be
separated by a multiple segment header. Only the named data fields will
be output [Default selects all columns].

Required Arguments
------------------

- *tracks* : -- One or more track data files (file names or GMTdatasets).

- **T** or **TAG** or **tag** : -- *tag="tagname"*\
   Specify the system tag for this compilation.

Optional Arguments
------------------

- **A** or **adjust** or **adjustments** : -- *adjustments=true*\
   Eliminate COEs by distributing the COE between the two tracks in proportion to
   track weight. These (dist, adjustment) spline knots files for each track and
   data column are called *track.column*.adj and are expected to be in the
   **$X2SYS_HOME**/*TAG* directory. The adjustments are only applied if the
   corresponding adjust file can be found [No residual adjustments].

- **E** or **segments** or **headers** : -- *segments=true*\
   Enhance ASCII output by writing GMT segment headers between data from each
   track [no segment headers].

- **F** or **fields** or **columns** : -- *columns="name1,name2,..."*\
   Give a comma-separated sub-set list of column names defined in the format
   definition file [Default selects all data columns].

- **I** or **exclude** or **ignore** : -- *exclude="listfile"*\
   Name of ASCII file with a list of track names (one per record) that should
   be excluded from consideration [Default includes all tracks].

- **L** or **corr** or **corrections** : -- *corrections=true* **|** *corrections="tablefile"*\
   Apply optimal corrections to columns where such corrections are available.
   Append the correction table to use [Default uses the correction table
   *TAG*_corrections.txt which is expected to reside in the **$X2SYS_HOME**/*TAG*
   directory]. For the format of this file, see Corrections below.

{{< include ../common_opts/opt_R.qmd >}}

- **S** or **skipnan** or **suppress** : -- *suppress=true*\
   Suppress output records where all the data columns are NaN [Default will
   output all records].

{{< include ../common_opts/opt_V.qmd >}}

{{< include ../common_opts/opt_bo.qmd >}}

Corrections
-----------

The correction table is an ASCII file with coefficients and parameters needed to
carry out corrections. This table is usually produced by {{< gmtref x2sys_solve >}}.
Comment records beginning with # are allowed. All correction records are of the form:

*trackID observation correction*

where *trackID* is the track name, *observation* is one of the abbreviations for an
observed field contained in files under this TAG, and *correction* consists of one
or more terms that will be **subtracted** from the observation before output.

Each term must have this syntax:

*factor*[\*[*function*]([*scale*](*abbrev*[-*origin*]))[^*power*]]

The *factor* is the amplitude of the basis function, while the optional *function*
can be one of sin, cos, or exp. The *abbrev* is one of the abbreviations for columns
known to this TAG, or one of the auxiliary terms **dist** (along-track distances),
**azim** (along-track azimuths), and **vel** (along-track speed).

Example corrections:

```
ABC z 7.1 1e-4*((time-T))
ABC obs 0.5*exp(-1e-3(lat))^1.5
ABC weight -1
ABC fuel 0.02*((dist))
```

Examples
--------

To extract all data from the old-style MGG supplement file c2104.gmt, recognized
by the tag GMT:

```julia
using GMT
D = x2sys_datalist("c2104.gmt", tag="GMT")
```

To extract (lon, lat, depth) for blockmean and surface using all files listed in
tracks.lis, defined by the tag TRK, but only data inside the specified area:

```julia
using GMT
D = x2sys_datalist("=tracks.lis", tag="TRK", columns="lon,lat,depth",
                   region=(40,-30,25,35))
```

To extract data with segment headers between tracks:

```julia
using GMT
D = x2sys_datalist("track1.gmt track2.gmt", tag="GMT", segments=true)
```

To apply corrections from a correction table:

```julia
using GMT
D = x2sys_datalist("tracks.gmt", tag="MGD77", corrections="mycorrections.txt")
```

See Also
--------

- {{< gmtref x2sys_init >}}, {{< gmtref x2sys_cross >}}, {{< gmtref x2sys_binlist >}}, {{< gmtref x2sys_get >}}, {{< gmtref x2sys_list >}}, {{< gmtref x2sys_solve >}}
- [Alphabetical Function List](../alphabetical.html)

```{julia}
#| echo: false
#| output: asis
using GMT
GMT.doc_source_links("x2sys_datalist")
```
