---
title: "Alphabetical Function List"
---

# Complete Alphabetical Function Reference

This page lists all documented functions in GMT.jl alphabetically.

::: {.callout-tip}
Use your browser's search function (Ctrl+F or Cmd+F) to quickly find a specific function.
:::

**Jump to:** [A](#a) | [B](#b) | [C](#c) | [D](#d) | [E](#e) | [F](#f) | [G](#g) | [H](#h) | [I](#i) | [K](#k) | [L](#l) | [M](#m) | [N](#n) | [O](#o) | [P](#p) | [Q](#q) | [R](#r) | [S](#s) | [T](#t) | [U](#u) | [V](#v) | [W](#w) | [X](#x) | [Y](#y) | [Z](#z)

---

## A {#a}

| Function | Category |
|----------|----------|
| [`ablines`](utilities/ablines.html) | Utilities |
| [`anaglyph`](utilities/anaglyph.html) | Utilities |
| [`analemma`](utilities/analemma.html) | Utilities |
| [`append2fig`](utilities/append2fig.html) | Utilities |
| [`arccircle`](gdalfuns/arccircle.html) | GDAL Functions |
| [`arcellipse`](gdalfuns/arcellipse.html) | GDAL Functions |
| [`arrows`](modules/arrows.html) | Modules |
| [`autocor`](utilities/autocor.html) | Utilities |
| [`autocov`](utilities/autocov.html) | Utilities |

## B {#b}

| Function | Category |
|----------|----------|
| [`band`](modules/band.html) | Modules |
| [`bar`](modules/bar.html) | Modules |
| [`bar3`](modules/bar3.html) | Modules |
| [`basemap`](modules/basemap.html) | Modules |
| [`bezier`](utilities/bezier.html) | Utilities |
| [`binarize`](imgproc/binarize.html) | Image Processing |
| [`binstats`](modules/binstats.html) | Modules |
| [`biplot`](modules/biplot.html) | Modules |
| [`blockmean`](modules/blockmean.html) | Modules |
| [`blockmedian`](modules/blockmedian.html) | Modules |
| [`blockmode`](modules/blockmode.html) | Modules |
| [`boundary`](gdalfuns/boundary.html) | GDAL Functions |
| [`boxes`](modules/boxes.html) | Modules |
| [`boxplot`](modules/boxplot.html) | Modules |
| [`bubblechart`](modules/bubblechart.html) | Modules |
| [`buffer`](gdalfuns/buffer.html) | GDAL Functions |
| [`buffergeo`](gdalfuns/buffergeo.html) | GDAL Functions |
| [`bwareaopen`](imgproc/bwareaopen.html) | Image Processing |
| [`bwconncomp`](imgproc/bwconncomp.html) | Image Processing |
| [`bwdist`](imgproc/bwdist.html) | Image Processing |
| [`bwdist_idx`](imgproc/bwdist_idx.html) | Image Processing |
| [`bwhitmiss`](imgproc/bwhitmiss.html) | Image Processing |
| [`bwlabel`](imgproc/bwlabel.html) | Image Processing |
| [`bwperim`](imgproc/bwperim.html) | Image Processing |
| [`bwskell`](imgproc/bwskell.html) | Image Processing |

## C {#c}

| Function | Category |
|----------|----------|
| [`cart2pol`](utilities/cart2pol.html) | Utilities |
| [`cart2sph`](utilities/cart2sph.html) | Utilities |
| [`cc2bw`](imgproc/cc2bw.html) | Image Processing |
| [`centroid`](gdalfuns/centroid.html) | GDAL Functions |
| [`circfit`](utilities/circfit.html) | Utilities |
| [`circgeo`](gdalfuns/circgeo.html) | GDAL Functions |
| [`circlepts`](utilities/circlepts.html) | Utilities |
| [`clip`](modules/clip.html) | Modules |
| [`coast`](modules/coast.html) | Modules |
| [`coastlinesproj`](utilities/coastlinesproj.html) | Utilities |
| [`colorbar`](modules/colorbar.html) | Modules |
| [`colorscale`](modules/colorscale.html) | Modules |
| [`concavehull`](gdalfuns/concavehull.html) | GDAL Functions |
| [`contains`](gdalfuns/contains.html) | GDAL Functions |
| [`contour`](modules/contour.html) | Modules |
| [`contourf`](modules/contourf.html) | Modules |
| [`conv`](utilities/conv.html) | Utilities |
| [`convexhull`](gdalfuns/convexhull.html) | GDAL Functions |
| [`cornerplot`](modules/cornerplot.html) | Modules |
| [`coupe`](modules/coupe.html) | Modules |
| [`cpt4dcw`](utilities/cpt4dcw.html) | Utilities |
| [`crop`](utilities/crop.html) | Utilities |
| [`crosses`](gdalfuns/crosses.html) | GDAL Functions |
| [`cube`](utilities/cube.html) | Utilities |
| [`cubeplot`](utilities/cubeplot.html) | Utilities |
| [`cubeslice`](utilities/cubeslice.html) | Utilities |
| [`cylinder`](utilities/cylinder.html) | Utilities |

## D {#d}

| Function | Category |
|----------|----------|
| [`date2doy`](utilities/date2doy.html) | Utilities |
| [`decorated`](modules/decorated.html) | Modules |
| [`delaunay`](gdalfuns/delaunay.html) | GDAL Functions |
| [`delrows`](utilities/delrows.html) | Utilities |
| [`density`](modules/density.html) | Modules |
| [`destroy`](gdalfuns/destroy.html) | GDAL Functions |
| [`df2ds`](utilities/df2ds.html) | Utilities |
| [`difference`](gdalfuns/difference.html) | GDAL Functions |
| [`disjoint`](gdalfuns/disjoint.html) | GDAL Functions |
| [`distance`](gdalfuns/distance.html) | GDAL Functions |
| [`dither`](gdalfuns/dither.html) | GDAL Functions |
| [`dodecahedron`](utilities/dodecahedron.html) | Utilities |
| [`doy2date`](utilities/doy2date.html) | Utilities |
| [`ds2df`](utilities/ds2df.html) | Utilities |

## E {#e}

| Function | Category |
|----------|----------|
| [`earthregions`](modules/earthregions.html) | Modules |
| [`earthtide`](modules/earthtide.html) | Modules |
| [`ecdfplot`](modules/ecdfplot.html) | Modules |
| [`ecmwf`](utilities/ecmwf.html) | Utilities |
| [`ellipse3D`](utilities/ellipse3D.html) | Utilities |
| [`enso`](utilities/enso.html) | Utilities |
| [`envelope`](gdalfuns/envelope.html) | GDAL Functions |
| [`envelope3d`](gdalfuns/envelope3d.html) | GDAL Functions |
| [`epsg2proj`](gdalfuns/epsg2proj.html) | GDAL Functions |
| [`epsg2wkt`](gdalfuns/epsg2wkt.html) | GDAL Functions |
| [`equals`](gdalfuns/equals.html) | GDAL Functions |
| [`era5time`](utilities/era5time.html) | Utilities |
| [`era5vars`](utilities/era5vars.html) | Utilities |
| [`eulermat`](utilities/eulermat.html) | Utilities |
| [`events`](modules/events.html) | Modules |
| [`extrude`](utilities/extrude.html) | Utilities |

## F {#f}

| Function | Category |
|----------|----------|
| [`feather`](modules/feather.html) | Modules |
| [`fields`](utilities/fields.html) | Utilities |
| [`fileparts`](utilities/fileparts.html) | Utilities |
| [`fill_between`](modules/fill_between.html) | Modules |
| [`fillnodata`](gdalfuns/fillnodata.html) | GDAL Functions |
| [`fillsinks`](imgproc/fillsinks.html) | Image Processing |
| [`filter1d`](modules/filter1d.html) | Modules |
| [`findpeaks`](utilities/findpeaks.html) | Utilities |
| [`fitcircle`](modules/fitcircle.html) | Modules |
| [`flatfv`](utilities/flatfv.html) | Utilities |
| [`flipdim`](utilities/flipdim.html) | Utilities |
| [`fliplr`](utilities/fliplr.html) | Utilities |
| [`flipud`](utilities/flipud.html) | Utilities |
| [`fourcolors`](utilities/fourcolors.html) | Utilities |
| [`fromWKT`](gdalfuns/fromWKT.html) | GDAL Functions |
| [`funcurve`](utilities/funcurve.html) | Utilities |
| [`fv2fv`](utilities/fv2fv.html) | Utilities |

## G {#g}

| Function | Category |
|----------|----------|
| [`gadm`](utilities/gadm.html) | Utilities |
| [`Gantijoin`](utilities/Gantijoin.html) | Utilities |
| [`Gcrossjoin`](utilities/Gcrossjoin.html) | Utilities |
| [`gd2gmt`](gdalfuns/gd2gmt.html) | GDAL Functions |
| [`gdalbuildvrt`](gdalfuns/gdalbuildvrt.html) | GDAL Functions |
| [`gdaldem`](gdalfuns/gdaldem.html) | GDAL Functions |
| [`gdaldrivers`](gdalfuns/gdaldrivers.html) | GDAL Functions |
| [`gdalgrid`](gdalfuns/gdalgrid.html) | GDAL Functions |
| [`gdalinfo`](gdalfuns/gdalinfo.html) | GDAL Functions |
| [`gdalrasterize`](gdalfuns/gdalrasterize.html) | GDAL Functions |
| [`gdalread`](gdalfuns/gdalread.html) | GDAL Functions |
| [`gdalshade`](gdalfuns/gdalshade.html) | GDAL Functions |
| [`gdaltranslate`](gdalfuns/gdaltranslate.html) | GDAL Functions |
| [`gdalvectortranslate`](gdalfuns/gdalvectortranslate.html) | GDAL Functions |
| [`gdalwarp`](gdalfuns/gdalwarp.html) | GDAL Functions |
| [`gdalwrite`](gdalfuns/gdalwrite.html) | GDAL Functions |
| [`geocoder`](utilities/geocoder.html) | Utilities |
| [`geod`](gdalfuns/geod.html) | GDAL Functions |
| [`geodesic`](gdalfuns/geodesic.html) | GDAL Functions |
| [`geodesicarea`](gdalfuns/geodesicarea.html) | GDAL Functions |
| [`geodetic2enu`](utilities/geodetic2enu.html) | Utilities |
| [`geomarea`](gdalfuns/geomarea.html) | GDAL Functions |
| [`geomlength`](gdalfuns/geomlength.html) | GDAL Functions |
| [`getattrib`](utilities/getattrib.html) | Utilities |
| [`getattribs`](utilities/getattribs.html) | Utilities |
| [`getband`](gdalfuns/getband.html) | GDAL Functions |
| [`getbyattrib`](utilities/getbyattrib.html) | Utilities |
| [`getdcw`](utilities/getdcw.html) | Utilities |
| [`getdriver`](gdalfuns/getdriver.html) | GDAL Functions |
| [`getgeom`](gdalfuns/getgeom.html) | GDAL Functions |
| [`getgeotransform`](gdalfuns/getgeotransform.html) | GDAL Functions |
| [`getlayer`](gdalfuns/getlayer.html) | GDAL Functions |
| [`getproj`](gdalfuns/getproj.html) | GDAL Functions |
| [`getprovider`](utilities/getprovider.html) | Utilities |
| [`getregion`](utilities/getregion.html) | Utilities |
| [`getres`](utilities/getres.html) | Utilities |
| [`Ginnerjoin`](utilities/Ginnerjoin.html) | Utilities |
| [`Gleftjoin`](utilities/Gleftjoin.html) | Utilities |
| [`gmt`](modules/gmt.html) | Modules |
| [`gmt2gd`](gdalfuns/gmt2gd.html) | GDAL Functions |
| [`gmt2kml`](modules/gmt2kml.html) | Modules |
| [`gmtbegin`](modules/gmtbegin.html) | Modules |
| [`gmtbinstats`](modules/gmtbinstats.html) | Modules |
| [`gmtconnect`](modules/gmtconnect.html) | Modules |
| [`gmtconvert`](modules/gmtconvert.html) | Modules |
| [`gmtend`](modules/gmtend.html) | Modules |
| [`gmtfig`](modules/gmtfig.html) | Modules |
| [`gmtgravmag3d`](modules/gmtgravmag3d.html) | Modules |
| [`gmthelp`](modules/gmthelp.html) | Modules |
| [`gmtinfo`](modules/gmtinfo.html) | Modules |
| [`gmtisf`](modules/gmtisf.html) | Modules |
| [`gmtlogo`](modules/gmtlogo.html) | Modules |
| [`gmtmath`](modules/gmtmath.html) | Modules |
| [`gmtread`](utilities/gmtread.html) | Utilities |
| [`gmtregress`](modules/gmtregress.html) | Modules |
| [`gmtselect`](modules/gmtselect.html) | Modules |
| [`gmtset`](modules/gmtset.html) | Modules |
| [`gmtsimplify`](modules/gmtsimplify.html) | Modules |
| [`gmtspatial`](modules/gmtspatial.html) | Modules |
| [`gmtsplit`](modules/gmtsplit.html) | Modules |
| [`gmtvector`](modules/gmtvector.html) | Modules |
| [`gmtwhich`](modules/gmtwhich.html) | Modules |
| [`gmtwrite`](utilities/gmtwrite.html) | Utilities |
| [`Gouterjoin`](utilities/Gouterjoin.html) | Utilities |
| [`graticules`](utilities/graticules.html) | Utilities |
| [`gravfft`](modules/gravfft.html) | Modules |
| [`gravmag3d`](modules/gravmag3d.html) | Modules |
| [`gravprisms`](modules/gravprisms.html) | Modules |
| [`graydist`](imgproc/graydist.html) | Image Processing |
| [`grays2cube`](imgproc/grays2cube.html) | Image Processing |
| [`grays2rgb`](imgproc/grays2rgb.html) | Image Processing |
| [`grd2cpt`](modules/grd2cpt.html) | Modules |
| [`grd2kml`](modules/grd2kml.html) | Modules |
| [`grd2xyz`](modules/grd2xyz.html) | Modules |
| [`grdblend`](modules/grdblend.html) | Modules |
| [`grdclip`](modules/grdclip.html) | Modules |
| [`grdcontour`](modules/grdcontour.html) | Modules |
| [`grdconvert`](modules/grdconvert.html) | Modules |
| [`grdcut`](modules/grdcut.html) | Modules |
| [`grdedit`](modules/grdedit.html) | Modules |
| [`grdfft`](modules/grdfft.html) | Modules |
| [`grdfill`](modules/grdfill.html) | Modules |
| [`grdfilter`](modules/grdfilter.html) | Modules |
| [`grdgradient`](modules/grdgradient.html) | Modules |
| [`grdgravmag3d`](modules/grdgravmag3d.html) | Modules |
| [`grdhisteq`](modules/grdhisteq.html) | Modules |
| [`grdimage`](modules/grdimage.html) | Modules |
| [`grdinfo`](modules/grdinfo.html) | Modules |
| [`grdinterpolate`](modules/grdinterpolate.html) | Modules |
| [`grdlandmask`](modules/grdlandmask.html) | Modules |
| [`grdmask`](modules/grdmask.html) | Modules |
| [`grdmath`](modules/grdmath.html) | Modules |
| [`grdpaste`](modules/grdpaste.html) | Modules |
| [`grdproject`](modules/grdproject.html) | Modules |
| [`grdrotater`](modules/grdrotater.html) | Modules |
| [`grdsample`](modules/grdsample.html) | Modules |
| [`grdseamount`](modules/grdseamount.html) | Modules |
| [`grdtrack`](modules/grdtrack.html) | Modules |
| [`grdtrend`](modules/grdtrend.html) | Modules |
| [`grdvector`](modules/grdvector.html) | Modules |
| [`grdview`](modules/grdview.html) | Modules |
| [`grdvolume`](modules/grdvolume.html) | Modules |
| [`greenspline`](modules/greenspline.html) | Modules |
| [`grid2img`](imgproc/grid2img.html) | Image Processing |
| [`grid2tri`](utilities/grid2tri.html) | Utilities |
| [`gridit`](utilities/gridit.html) | Utilities |
| [`Grightjoin`](utilities/Grightjoin.html) | Utilities |
| [`groupby`](utilities/groupby.html) | Utilities |
| [`Gsemijoin`](utilities/Gsemijoin.html) | Utilities |
| [`gunique`](utilities/gunique.html) | Utilities |

## H {#h}

| Function | Category |
|----------|----------|
| [`hampel`](utilities/hampel.html) | Utilities |
| [`haralick`](imgproc/haralick.html) | Image Processing |
| [`hband`](modules/hband.html) | Modules |
| [`histogram`](modules/histogram.html) | Modules |
| [`hlines`](utilities/hlines.html) | Utilities |
| [`hspan`](modules/hspan.html) | Modules |

## I {#i}

| Function | Category |
|----------|----------|
| [`icosahedron`](utilities/icosahedron.html) | Utilities |
| [`image`](modules/image.html) | Modules |
| [`imagesc`](utilities/imagesc.html) | Utilities |
| [`imbothat`](imgproc/imbothat.html) | Image Processing |
| [`imclearborder`](imgproc/imclearborder.html) | Image Processing |
| [`imclose`](imgproc/imclose.html) | Image Processing |
| [`imcomplement`](imgproc/imcomplement.html) | Image Processing |
| [`imdilate`](imgproc/imdilate.html) | Image Processing |
| [`imerode`](imgproc/imerode.html) | Image Processing |
| [`imfill`](imgproc/imfill.html) | Image Processing |
| [`imfilter`](imgproc/imfilter.html) | Image Processing |
| [`img2grd`](modules/img2grd.html) | Modules |
| [`img2grid`](utilities/img2grid.html) | Utilities |
| [`imhdome`](imgproc/imhdome.html) | Image Processing |
| [`imhmax`](imgproc/imhmax.html) | Image Processing |
| [`imhmin`](imgproc/imhmin.html) | Image Processing |
| [`immorphgrad`](imgproc/immorphgrad.html) | Image Processing |
| [`imopen`](imgproc/imopen.html) | Image Processing |
| [`importEPSG`](gdalfuns/importEPSG.html) | GDAL Functions |
| [`importPROJ4`](gdalfuns/importPROJ4.html) | GDAL Functions |
| [`importWKT`](gdalfuns/importWKT.html) | GDAL Functions |
| [`imrankfilter`](imgproc/imrankfilter.html) | Image Processing |
| [`imreconstruct`](imgproc/imreconstruct.html) | Image Processing |
| [`imregionalmax`](imgproc/imregionalmax.html) | Image Processing |
| [`imregionalmin`](imgproc/imregionalmin.html) | Image Processing |
| [`imresize`](imgproc/imresize.html) | Image Processing |
| [`imsegment`](imgproc/imsegment.html) | Image Processing |
| [`imshow`](utilities/imshow.html) | Utilities |
| [`imsobel`](imgproc/imsobel.html) | Image Processing |
| [`imtophat`](imgproc/imtophat.html) | Image Processing |
| [`inbbox`](gdalfuns/inbbox.html) | GDAL Functions |
| [`ind2bool`](utilities/ind2bool.html) | Utilities |
| [`ind2rgb`](utilities/ind2rgb.html) | Utilities |
| [`info`](utilities/info.html) | Utilities |
| [`inpolygon`](utilities/inpolygon.html) | Utilities |
| [`inset`](modules/inset.html) | Modules |
| [`intersection`](gdalfuns/intersection.html) | GDAL Functions |
| [`intersects`](gdalfuns/intersects.html) | GDAL Functions |
| [`invgeod`](gdalfuns/invgeod.html) | GDAL Functions |
| [`inwhichpolygon`](utilities/inwhichpolygon.html) | Utilities |
| [`isclockwise`](utilities/isclockwise.html) | Utilities |
| [`isnodata`](utilities/isnodata.html) | Utilities |
| [`isodata`](imgproc/isodata.html) | Image Processing |
| [`ISOtime2unix`](utilities/ISOtime2unix.html) | Utilities |
| [`isoutlier`](utilities/isoutlier.html) | Utilities |

## K {#k}

| Function | Category |
|----------|----------|
| [`keeling`](utilities/keeling.html) | Utilities |
| [`kmeans`](utilities/kmeans.html) | Utilities |
| [`kml2gmt`](modules/kml2gmt.html) | Modules |

## L {#l}

| Function | Category |
|----------|----------|
| [`lasread`](utilities/lasread.html) | Utilities |
| [`laswrite`](utilities/laswrite.html) | Utilities |
| [`lazinfo`](utilities/lazinfo.html) | Utilities |
| [`lazread`](utilities/lazread.html) | Utilities |
| [`lazwrite`](utilities/lazwrite.html) | Utilities |
| [`leepacific`](utilities/leepacific.html) | Utilities |
| [`legend`](modules/legend.html) | Modules |
| [`lelandshade`](utilities/lelandshade.html) | Utilities |
| [`linearfitxy`](utilities/linearfitxy.html) | Utilities |
| [`lines`](modules/lines.html) | Modules |
| [`linspace`](utilities/linspace.html) | Utilities |
| [`listecmwfvars`](utilities/listecmwfvars.html) | Utilities |
| [`loft`](utilities/loft.html) | Utilities |
| [`logo`](modules/gmtlogo.html) | Modules |
| [`logspace`](utilities/logspace.html) | Utilities |
| [`lonlat2xy`](gdalfuns/lonlat2xy.html) | GDAL Functions |
| [`lowess`](utilities/lowess.html) | Utilities |
| [`loxodrome`](gdalfuns/loxodrome.html) | GDAL Functions |
| [`loxodrome_direct`](gdalfuns/loxodrome_direct.html) | GDAL Functions |
| [`loxodrome_inverse`](gdalfuns/loxodrome_inverse.html) | GDAL Functions |

## M {#m}

| Function | Category |
|----------|----------|
| [`mad`](utilities/mad.html) | Utilities |
| [`magic`](utilities/magic.html) | Utilities |
| [`magref`](modules/magref.html) | Modules |
| [`makecpt`](modules/makecpt.html) | Modules |
| [`makeDCWs`](utilities/makeDCWs.html) | Utilities |
| [`mapproject`](modules/mapproject.html) | Modules |
| [`mapsize2region`](utilities/mapsize2region.html) | Utilities |
| [`maregrams`](utilities/maregrams.html) | Utilities |
| [`marginalhist`](modules/marginalhist.html) | Modules |
| [`mask`](modules/mask.html) | Modules |
| [`mat2ds`](utilities/mat2ds.html) | Utilities |
| [`mat2grid`](utilities/mat2grid.html) | Utilities |
| [`mat2img`](utilities/mat2img.html) | Utilities |
| [`mbgetdata`](utilities/mbgetdata.html) | Utilities |
| [`mbimport`](utilities/mbimport.html) | Utilities |
| [`mblevitus`](utilities/mblevitus.html) | Utilities |
| [`mbsvplist`](utilities/mbsvplist.html) | Utilities |
| [`meca`](modules/meca.html) | Modules |
| [`meshgrid`](utilities/meshgrid.html) | Utilities |
| [`meteostat`](utilities/meteostat.html) | Utilities |
| [`mgd77magref`](modules/mgd77magref.html) | Modules |
| [`mksymbol`](utilities/mksymbol.html) | Utilities |
| [`mosaic`](utilities/mosaic.html) | Utilities |
| [`movie`](modules/movie.html) | Modules |

## N {#n}

| Function | Category |
|----------|----------|
| [`nanmean`](utilities/nanmean.html) | Utilities |
| [`nanstd`](utilities/nanstd.html) | Utilities |
| [`nearneighbor`](modules/nearneighbor.html) | Modules |

## O {#o}

| Function | Category |
|----------|----------|
| [`octahedron`](utilities/octahedron.html) | Utilities |
| [`ODE2ds`](utilities/ODE2ds.html) | Utilities |
| [`ogr2ogr`](gdalfuns/ogr2ogr.html) | GDAL Functions |
| [`okada`](utilities/okada.html) | Utilities |
| [`orbits`](utilities/orbits.html) | Utilities |
| [`orthodrome`](gdalfuns/orthodrome.html) | GDAL Functions |
| [`overlaps`](gdalfuns/overlaps.html) | GDAL Functions |

## P {#p}

| Function | Category |
|----------|----------|
| [`padarray`](imgproc/padarray.html) | Image Processing |
| [`parallelplot`](modules/parallelplot.html) | Modules |
| [`parkergrav`](utilities/parkergrav.html) | Utilities |
| [`parkermag`](utilities/parkermag.html) | Utilities |
| [`pastplates`](utilities/pastplates.html) | Utilities |
| [`pca`](utilities/pca.html) | Utilities |
| [`pcolor`](utilities/pcolor.html) | Utilities |
| [`peaks`](utilities/peaks.html) | Utilities |
| [`piechart`](modules/piechart.html) | Modules |
| [`plot`](modules/plot.html) | Modules |
| [`plot3`](modules/plot3.html) | Modules |
| [`plot3d`](modules/plot3d.html) | Modules |
| [`plotlinefit`](utilities/plotlinefit.html) | Utilities |
| [`plotyy`](utilities/plotyy.html) | Utilities |
| [`pointalongline`](gdalfuns/pointalongline.html) | GDAL Functions |
| [`pol2cart`](utilities/pol2cart.html) | Utilities |
| [`polyfit`](utilities/polyfit.html) | Utilities |
| [`polygonize`](gdalfuns/polygonize.html) | GDAL Functions |
| [`polygonlevels`](utilities/polygonlevels.html) | Utilities |
| [`polyunion`](gdalfuns/polyunion.html) | GDAL Functions |
| [`polyval`](utilities/polyval.html) | Utilities |
| [`pow`](utilities/pow.html) | Utilities |
| [`proj2wkt`](gdalfuns/proj2wkt.html) | GDAL Functions |
| [`project`](modules/project.html) | Modules |
| [`psbasemap`](modules/psbasemap.html) | Modules |
| [`psclip`](modules/psclip.html) | Modules |
| [`pscoast`](modules/pscoast.html) | Modules |
| [`pscontour`](modules/pscontour.html) | Modules |
| [`psconvert`](modules/psconvert.html) | Modules |
| [`pscoupe`](modules/pscoupe.html) | Modules |
| [`psevents`](modules/psevents.html) | Modules |
| [`pshistogram`](modules/pshistogram.html) | Modules |
| [`psimage`](modules/psimage.html) | Modules |
| [`pslegend`](modules/pslegend.html) | Modules |
| [`psmask`](modules/psmask.html) | Modules |
| [`psmeca`](modules/psmeca.html) | Modules |
| [`psrose`](modules/psrose.html) | Modules |
| [`psscale`](modules/psscale.html) | Modules |
| [`pssolar`](modules/pssolar.html) | Modules |
| [`psternary`](modules/psternary.html) | Modules |
| [`pstext`](modules/pstext.html) | Modules |
| [`psvelo`](modules/psvelo.html) | Modules |
| [`pswiggle`](modules/pswiggle.html) | Modules |
| [`psxy`](modules/psxy.html) | Modules |
| [`psxyz`](modules/psxyz.html) | Modules |

## Q {#q}

| Function | Category |
|----------|----------|
| [`qqnorm`](modules/qqnorm.html) | Modules |
| [`qqplot`](modules/qqplot.html) | Modules |
| [`quadbounds`](utilities/quadbounds.html) | Utilities |
| [`quadkey`](utilities/quadkey.html) | Utilities |
| [`quiver`](modules/quiver.html) | Modules |

## R {#r}

| Function | Category |
|----------|----------|
| [`radar`](modules/radar.html) | Modules |
| [`randgeo`](gdalfuns/randgeo.html) | GDAL Functions |
| [`randinpolygon`](utilities/randinpolygon.html) | Utilities |
| [`rasterzones`](utilities/rasterzones.html) | Utilities |
| [`readgeom`](gdalfuns/readgeom.html) | GDAL Functions |
| [`readraster`](gdalfuns/readraster.html) | GDAL Functions |
| [`regiongeog`](utilities/regiongeog.html) | Utilities |
| [`regress`](modules/regress.html) | Modules |
| [`remotegrid`](utilities/remotegrid.html) | Utilities |
| [`replicant`](utilities/replicant.html) | Utilities |
| [`rescale`](utilities/rescale.html) | Utilities |
| [`resetGMT`](utilities/resetGMT.html) | Utilities |
| [`revolve`](utilities/revolve.html) | Utilities |
| [`rgb2gray`](imgproc/rgb2gray.html) | Image Processing |
| [`rgb2lab`](imgproc/rgb2lab.html) | Image Processing |
| [`rgb2YCbCr`](imgproc/rgb2YCbCr.html) | Image Processing |
| [`rgb2ycbcr`](imgproc/rgb2ycbcr.html) | Image Processing |
| [`rose`](modules/rose.html) | Modules |
| [`rotate`](utilities/rotate.html) | Utilities |

## S {#s}

| Function | Category |
|----------|----------|
| [`sample1d`](modules/sample1d.html) | Modules |
| [`scatter`](modules/scatter.html) | Modules |
| [`scatter3`](modules/scatter3.html) | Modules |
| [`sealand`](utilities/sealand.html) | Utilities |
| [`seismicity`](modules/seismicity.html) | Modules |
| [`setproj!`](gdalfuns/setproj!.html) | GDAL Functions |
| [`showfig`](modules/showfig.html) | Modules |
| [`simplify`](gdalfuns/simplify.html) | GDAL Functions |
| [`slicecube`](utilities/slicecube.html) | Utilities |
| [`solar`](modules/solar.html) | Modules |
| [`sortslicesperm`](utilities/sortslicesperm.html) | Utilities |
| [`spatialjoin`](utilities/spatialjoin.html) | Utilities |
| [`spectrum1d`](modules/spectrum1d.html) | Modules |
| [`sph2cart`](utilities/sph2cart.html) | Utilities |
| [`sphdistance`](modules/sphdistance.html) | Modules |
| [`sphere`](utilities/sphere.html) | Utilities |
| [`sphinterpolate`](modules/sphinterpolate.html) | Modules |
| [`sphtriangulate`](modules/sphtriangulate.html) | Modules |
| [`spinmat`](utilities/spinmat.html) | Utilities |
| [`squeeze`](utilities/squeeze.html) | Utilities |
| [`stackgrids`](utilities/stackgrids.html) | Utilities |
| [`stairs`](modules/stairs.html) | Modules |
| [`stats`](utilities/stats.html) | Utilities |
| [`stem`](modules/stem.html) | Modules |
| [`stereonet`](utilities/stereonet.html) | Utilities |
| [`streamlines`](utilities/streamlines.html) | Utilities |
| [`strel`](imgproc/strel.html) | Image Processing |
| [`subplot`](modules/subplot.html) | Modules |
| [`sunsetrise`](utilities/sunsetrise.html) | Utilities |
| [`surf2fv`](utilities/surf2fv.html) | Utilities |
| [`surface`](modules/surface.html) | Modules |
| [`symdifference`](gdalfuns/symdifference.html) | GDAL Functions |

## T {#t}

| Function | Category |
|----------|----------|
| [`tern2cart`](utilities/tern2cart.html) | Utilities |
| [`ternary`](modules/ternary.html) | Modules |
| [`terramar`](utilities/terramar.html) | Utilities |
| [`tetrahedron`](utilities/tetrahedron.html) | Utilities |
| [`text`](modules/text.html) | Modules |
| [`text_record`](utilities/text_record.html) | Utilities |
| [`texture_img`](utilities/texture_img.html) | Utilities |
| [`theme`](utilities/theme.html) | Utilities |
| [`tic`](utilities/tic.html) | Utilities |
| [`toc`](utilities/toc.html) | Utilities |
| [`togglemask`](utilities/togglemask.html) | Utilities |
| [`toPROJ4`](gdalfuns/toPROJ4.html) | GDAL Functions |
| [`torus`](utilities/torus.html) | Utilities |
| [`touches`](gdalfuns/touches.html) | GDAL Functions |
| [`toWKT`](gdalfuns/toWKT.html) | GDAL Functions |
| [`translate`](utilities/translate.html) | Utilities |
| [`trend1d`](modules/trend1d.html) | Modules |
| [`trend2d`](modules/trend2d.html) | Modules |
| [`triangulate`](modules/triangulate.html) | Modules |
| [`triplot`](modules/triplot.html) | Modules |
| [`trisurf`](modules/trisurf.html) | Modules |

## U {#u}

| Function | Category |
|----------|----------|
| [`uniqueind`](utilities/uniqueind.html) | Utilities |
| [`upGMT`](utilities/upGMT.html) | Utilities |

## V {#v}

| Function | Category |
|----------|----------|
| [`vband`](modules/vband.html) | Modules |
| [`vecangles`](utilities/vecangles.html) | Utilities |
| [`vector_attrib`](utilities/vector_attrib.html) | Utilities |
| [`velo`](modules/velo.html) | Modules |
| [`violin`](modules/violin.html) | Modules |
| [`viz`](utilities/viz.html) | Utilities |
| [`vizpdf`](utilities/vizpdf.html) | Utilities |
| [`vlines`](utilities/vlines.html) | Utilities |
| [`vspan`](modules/vspan.html) | Modules |

## W {#w}

| Function | Category |
|----------|----------|
| [`weather`](utilities/weather.html) | Utilities |
| [`whereami`](utilities/whereami.html) | Utilities |
| [`whittaker`](utilities/whittaker.html) | Utilities |
| [`wiggle`](modules/wiggle.html) | Modules |
| [`windbarbs`](modules/windbarbs.html) | Modules |
| [`within`](gdalfuns/within.html) | GDAL Functions |
| [`wkt2proj`](gdalfuns/wkt2proj.html) | GDAL Functions |
| [`wmsinfo`](utilities/wmsinfo.html) | Utilities |
| [`wmsread`](utilities/wmsread.html) | Utilities |
| [`wmstest`](utilities/wmstest.html) | Utilities |
| [`worldrectangular`](utilities/worldrectangular.html) | Utilities |
| [`worldrectcoast`](utilities/worldrectcoast.html) | Utilities |
| [`worldrectgrid`](utilities/worldrectgrid.html) | Utilities |

## X {#x}

| Function | Category |
|----------|----------|
| [`xcorr`](utilities/xcorr.html) | Utilities |
| [`xcov`](utilities/xcov.html) | Utilities |
| [`xy2lonlat`](gdalfuns/xy2lonlat.html) | GDAL Functions |
| [`xyz2grd`](modules/xyz2grd.html) | Modules |
| [`xyzw2cube`](utilities/xyzw2cube.html) | Utilities |

## Y {#y}

| Function | Category |
|----------|----------|
| [`yeardecimal`](utilities/yeardecimal.html) | Utilities |

## Z {#z}

| Function | Category |
|----------|----------|
| [`zonal_statistics`](utilities/zonal_statistics.html) | Utilities |
| [`zonal_stats`](utilities/zonal_stats.html) | Utilities |
| [`zscores`](utilities/zscores.html) | Utilities |

